from . import route_plan
from . import trailer
from . import trailer_history
from . import plan_trip_lines
from . import plan_trip_waybill
from . import plan_trip_product
from . import day_plan_trip
from . import product
from . import account_payment
from . import commission_config
from . import res_partner
from . import fleet_vehicle
