{
    'name': 'HR Payroll Customization',
    'version': '1.0.0',
    'author': '7thcomputing',
    'license': 'AGPL-3',
    'category': 'Employee',
    'website': 'http://7thcomputing.com',
    'description': """
HR Payroll Customization
    """,
    'depends': ['base',
                'hr',
                'hr_payroll',
                'hr_payroll_account',
                'hr_allowance',
                'hr_deduction',
                'hr_loan',
                'hr_insurance',
                'hr_public_holiday',
                'job_grade','hr_ext',
                'mail'],
    'data': [
        'security/ir.model.access.csv',
        'data/work_entry_type.xml',
        'data/hr_basic_rule_data.xml',
        'data/hr_payslip_data.xml',
        'data/salary_income_tax_rules.xml',
        'data/hr_allowance_deduction_data.xml',
        'data/hr_payslip_custom.xml',
        'reports/report_payroll_wizard.xml',
        'reports/report_yearly_tax_wizard.xml',
        'views/hr_payslip_view.xml',
        'views/job_grade_view.xml',
        'views/hr_salary_view.xml',
        'views/hr_contract_view.xml',
        'views/employee_sale_achievement_view.xml',
        'reports/bank_and_payroll_wizard.xml',
        'wizards/draft_payslip_view.xml',
        'wizards/compute_payslip_view.xml',
    ],    
    'installable': True,
    'auto_install': False,
}
