# -*- coding: utf-8 -*-
from . import auth
from . import model__report
from . import model__hr_employee
from . import model__hr_department
from . import model__hr_job
from . import model__hr_leave
from . import model__hr_leave_type
from . import model__travel_request
from . import model__summary_request
from . import model__hr_attendance
from . import model__ot_request
from . import model__hr_employee_category
from . import model__ot_request_line
from . import model__res_users
from . import model__hr_loan
from . import model__hr_travel_type
from . import model__hr_payslip
from . import model__hr_announcement
from . import model__hr_warning
from . import model__hr_reward
from . import model__hr_employee_document
from . import model__product_category
from . import model__travel_request_allowance
from . import model__hr_pocket_expense
from . import model__hr_travel_expense
from . import model__hr_pocket_expense_line
from . import model__hr_travel_expense_line
from . import model__fleet_vehicle
from . import model__maintenance_request
from . import model__route_plan
from . import model__one_signal_notification_message
from . import model__employee_performance
from . import model__documents_document
from . import model__insurance_type
from . import model__plan_trip_product
from . import model__plan_trip_waybill
from . import model__day_plan_trip
from . import model__stock_location
from . import model__hr_insurance
from . import model__hr_attendance_raw
from . import model__day_trip_expense
from . import model__trip_fuel_in
from . import model__fleet_insurance
from . import model__hr_claims
from . import model__fleet_insurance_type
from . import model__maintenance_product
from . import model__fleet_vehicle_log_fuel
from . import model__trip_expense
from . import model__admin_trip_expense
from . import model__admin_trip_expense_line
from . import model__fuel_tank
from . import model__hr_resignation
from . import model__hr_promotion
