from . import hr
from . import insurance_type
from . import hr_leave_type
from . import hr_employee
from . import res_branch
from . import res_company
from . import hr_department
from . import product
from . import hr_pocket_expense
from . import hr_travel_expense
from . import account_move
from . import icloud_transaction
from . import product_template
from . import admin_trip_expense
from . import account_move_line
from . import account_payment
from . import hr_job_benefit_config
from . import  res_users
from . import hr_fiscal_year